global:
  scrape_interval: 10s 

scrape_configs:
- job_name: broker
  scrape_interval: 10s
  scrape_timeout: 10s
  scheme: http
  static_configs:
    - targets: ["broker-1:29101", "broker-2:29102", "broker-3:29103"]